### ISSUE TITLE
is there any memory leak?

### ISSUE THREAD

**Issue by YeHuanjie** [Forceflow/trimesh2#23]
asan reports some memory leak, is this false alarm?
==15180==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 496 byte(s) in 1 object(s) allocated from:
    #0 0x7effd55c3532 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99532)
    #1 0x40d640 in trimesh::TriMesh::read(char const*) (/home/tplink/mechanical_arm/test_trimesh/build/main+0x40d640)

Indirect leak of 919800 byte(s) in 1 object(s) allocated from:
    #0 0x7effd55c3532 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99532)
    #1 0x40951e in trimesh::read_faces_asc(_IO_FILE*, trimesh::TriMesh*, int, int, int, int, bool) (/home/tplink/mechanical_arm/test_trimesh/build/main+0x40951e)

Indirect leak of 919800 byte(s) in 2 object(s) allocated from:
    #0 0x7effd55c3532 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99532)
    #1 0x40f3b3 in std::vector<trimesh::Vec<3ul, float>, std::allocator<trimesh::Vec<3ul, float> > >::_M_fill_insert(__gnu_cxx::__normal_iterator<trimesh::Vec<3ul, float>*, std::vector<trimesh::Vec<3ul, float>, std::allocator<trimesh::Vec<3ul, float> > > >, unsigned long, trimesh::Vec<3ul, float> const&) (/home/tplink/mechanical_arm/test_trimesh/build/main+0x40f3b3)

Indirect leak of 459900 byte(s) in 1 object(s) allocated from:
    #0 0x7effd55c3532 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99532)
    #1 0x40f753 in std::vector<trimesh::Color, std::allocator<trimesh::Color> >::_M_fill_insert(__gnu_cxx::__normal_iterator<trimesh::Color*, std::vector<trimesh::Color, std::allocator<trimesh::Color> > >, unsigned long, trimesh::Color const&) (/home/tplink/mechanical_arm/test_trimesh/build/main+0x40f753)

**Comment by YeHuanjie** [comment]
i rebuild this repo with cmakelist, found memory leak at test demo:

```
#include "TriMesh.h"
#include <cstdlib>
#include <iostream>
using namespace trimesh;
using namespace std;

int main(int argc, char *argv[])
{
        const char *filename = "foo.ply";
        TriMesh *m = TriMesh::read(filename);
        if (!m)
                exit(1);

        cout << "There are " << m->vertices.size() << " vertices" << endl;
        cout << "Vertex 0 is at " << m->vertices[0] << endl;

        // Convert triangle strips to faces, if necessary
        m->need_faces();
        cout << "Face 0 has vertices " << m->faces[0][0] << ", "
             << m->faces[0][1] << ", and " << m->faces[0][2] << endl;

        m->need_normals();
        cout << "Vertex 0 has normal " << m->normals[0] << endl;

        // bug is here. there is a new in read, bug no delete at the end 
        delete m;
}
```
